build: false

image: Visual Studio 2015

platform:
  - x64

environment:
  matrix:
    - MINICONDA: C:\xtensor-conda

init:
  # Install miniconda
  - "ECHO %MINICONDA%"
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
  - ps: if($env:Platform -eq "x64"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"}
  - ps: if($env:Platform -eq "x86"){Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86.exe' C:\Miniconda.exe; echo "Done"}
  - cmd: C:\Miniconda.exe /S /D=C:\xtensor-conda
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"
  # Download most recent Julia Windows binary
  - ps: if($env:Platform -eq "x64"){(new-object net.webclient).DownloadFile(
        $("https://julialang-s3.julialang.org/bin/winnt/x64/1.0/julia-1.0.1-win64.exe"),
        "C:\projects\julia-binary.exe")}
  - ps: if($env:Platform -eq "x86"){(new-object net.webclient).DownloadFile(
        $("https://julialang-s3.julialang.org/bin/winnt/x86/1.0/julia-1.0.1-win32.exe"),
        "C:\projects\julia-binary.exe")}
  # Run installer silently, output to C:\projects\julia-build
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia-build

install:
  # Conda install cmake
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install m2w64-toolchain cmake -c conda-forge
  # Remove sh from PATH
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set MINGW_PATH=%MINICONDA%\\Library\\mingw-w64\\bin
  - set PATH=%MINGW_PATH%;%PATH%
  # Install CxxWrap
  - set BUILD_ON_WINDOWS=1
  - C:\projects\julia-build\bin\julia -E "using Pkg; Pkg.add(PackageSpec(name=\"CxxWrap\", version=\"0.8.1\"))"
  - C:\projects\julia-build\bin\julia --project=. -E "using Pkg; Pkg.build();"

build_script:
  - C:\projects\julia-build\bin\julia --project=. -E "using Pkg; Pkg.test()"
